name: release

on: 
  push:
    tags:
      - '*'

jobs:
  build-etwenumerator:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd

    strategy:
      matrix:
        arch:
          - name: x64
            vs_name: amd64
            

    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 1
          submodules: true

      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch.vs_name }}
          sdk: 10.0.26100.0
          vsversion: 2022

      - name: Build the EtwEnumerator DLL (${{ matrix.arch.vs_name }})
        working-directory: .
        run: |
          cmake --preset=ninja-${{ matrix.arch.name }}-release
          cmake --build --preset=ninja-${{ matrix.arch.name }}-release

      - uses: actions/upload-artifact@main
        with:
          name: build.${{ matrix.arch.name }}
          path: build

  
  build-and-publish-metadata:
    needs: build-etwenumerator
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd

    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 1
          submodules: true
      
      - uses: actions/download-artifact@main
        with:
          pattern: build.*
          path: build

      - uses: actions/setup-dotnet@main
        with:
          dotnet-version: 9.0.x

      - run: |
          Invoke-WebRequest -OutFile Update-AssemblyInfoVersionFiles.ps1 https://gist.githubusercontent.com/lowleveldesign/663de4e0d5a071f938e6f7c82d7ca9a0/raw/Update-AssemblyInfoVersionFiles.ps1
          ./Update-AssemblyInfoVersionFiles.ps1
        shell: pwsh

      - name: Build metadata
        working-directory: src
        run: dotnet build -c Release -p:GeneratePackageOnBuild=true

      - run: dotnet nuget push -s https://api.nuget.org/v3/index.json -k "$env:NUGET_KEY" EtwEnumerator.Win32Metadata.*.nupkg
        shell: pwsh
        env:
          NUGET_KEY: ${{ secrets.NUGET_KEY }}
        working-directory: src/bin/Release

      - uses: actions/upload-artifact@main
        with:
          name: EtwEnumerator.winmd
          path: src/winmd/EtwEnumerator.winmd

      - uses: actions/upload-artifact@main
        with:
          name: Nuget package
          path: src/bin/Release/EtwEnumerator.Win32Metadata.*.nupkg
